"""new table structure for story, syllable and annotation

Revision ID: 7affcc210b84
Revises: ce79c43745d0
Create Date: 2018-10-22 09:23:31.936187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7affcc210b84'
down_revision = 'ce79c43745d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('syllable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('frag_nbr', sa.SmallInteger(), nullable=False),
    sa.Column('line_nbr', sa.SmallInteger(), nullable=False),
    sa.Column('word_nbr', sa.SmallInteger(), nullable=False),
    sa.Column('syll_nbr', sa.SmallInteger(), nullable=False),
    sa.Column('syllable', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllable_story_id'), 'syllable', ['story_id'], unique=False)
    op.create_table('annotation_new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('syllable_id', sa.Integer(), nullable=False),
    sa.Column('stressed', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fragment_done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['syllable_id'], ['syllable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_new_user_id'), 'annotation_new', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_new_user_id'), table_name='annotation_new')
    op.drop_table('annotation_new')
    op.drop_index(op.f('ix_syllable_story_id'), table_name='syllable')
    op.drop_table('syllable')
    op.drop_table('story')
    # ### end Alembic commands ###
