"""added 2 fields to the user db

Revision ID: 9f564c1e763a
Revises: 
Create Date: 2018-11-19 13:36:28.550486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f564c1e763a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('middledutch', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'middledutch')
    op.drop_column('user', 'language')
    # ### end Alembic commands ###
