"""empty message

Revision ID: bf8655c95d4d
Revises: 7affcc210b84
Create Date: 2018-10-23 16:00:42.400009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8655c95d4d'
down_revision = '7affcc210b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragment_story_id'), 'fragment', ['story_id'], unique=False)
    op.add_column('syllable', sa.Column('frag_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_syllable_frag_id'), 'syllable', ['frag_id'], unique=False)
    op.drop_index('ix_syllable_story_id', table_name='syllable')
    op.drop_constraint(None, 'syllable', type_='foreignkey')
    op.create_foreign_key(None, 'syllable', 'fragment', ['frag_id'], ['id'])
    op.drop_column('syllable', 'story_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syllable', sa.Column('story_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'syllable', type_='foreignkey')
    op.create_foreign_key(None, 'syllable', 'story', ['story_id'], ['id'])
    op.create_index('ix_syllable_story_id', 'syllable', ['story_id'], unique=False)
    op.drop_index(op.f('ix_syllable_frag_id'), table_name='syllable')
    op.drop_column('syllable', 'frag_id')
    op.drop_index(op.f('ix_fragment_story_id'), table_name='fragment')
    op.drop_table('fragment')
    # ### end Alembic commands ###
